### ISSUE TITLE
About Data Pre-processing

### ISSUE THREAD

**Issue by FZH1802** [JunbongJang/contour-tracking#1]
where the file "tracking_points_labeling_GUI.py" and others?
i don't find there in youe github source code repositories. Can you provide there file?
Thanks!

**Comment by JunbongJang** [comment]
Thank you for pointing this out!
I will upload them after refactoring to make them easy to use.

**Comment by JunbongJang** [comment]
I updated Readme and uploaded the codes that you requested! 
Please feel free to ask any questions if you encounter any problems after running it.
